version: 2.1

orbs:
  github: circleci/github-cli@1.0.0

jobs:
  build-and-publish:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: |
          curl -L https://go.dev/dl/go1.23.0.linux-amd64.tar.gz | sudo tar -xzC /usr/local
          echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
          source ~/.bashrc
      - run: go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
      - run: |
          # Build for multiple architectures
          echo "Building for AMD64..."
          GOOS=linux GOARCH=amd64 go build -o bin/somana-linux-amd64 ./cmd/server
          
          echo "Building for ARM64..."
          GOOS=linux GOARCH=arm64 go build -o bin/somana-linux-arm64 ./cmd/server
          
          echo "Building for macOS AMD64..."
          GOOS=darwin GOARCH=amd64 go build -o bin/somana-darwin-amd64 ./cmd/server
          
          echo "Building for macOS ARM64 (Apple Silicon)..."
          GOOS=darwin GOARCH=arm64 go build -o bin/somana-darwin-arm64 ./cmd/server
          
          echo "Build complete! Binaries:"
          ls -la bin/
      - github/setup-github-cli
      - run: |
          # Auto-increment version based on commit count
          COMMIT_COUNT=$(git rev-list --count HEAD)
          VERSION="v1.0.$COMMIT_COUNT"
          echo "Using auto-incremented version: $VERSION"
          
          # Publish OpenAPI spec with the same version
          echo "Publishing OpenAPI spec with version: $VERSION"
          make publish-openapi VERSION=$VERSION
          
          # Create GitHub release with all binaries
          gh release create $VERSION \
            bin/somana-linux-amd64 \
            bin/somana-linux-arm64 \
            bin/somana-darwin-amd64 \
            bin/somana-darwin-arm64 \
            --title "Somana $VERSION" \
            --notes "Somana $VERSION - Built and tested on CircleCI with multi-architecture support for Linux and macOS"

workflows:
  version: 2
  build-and-publish:
    jobs:
      - build-and-publish:
          filters:
            branches:
              only: main